stages:
  - build

build:
  stage: build
  image: golang:alpine
  script:
    - apk add ca-certificates gcc musl-dev git build-base
    - make pull
    - go test -v -race ./...
    - go test -bench . -benchmem ./...
    - make build_all
  only:
    - master
  tags:
    - gitlab-org
  artifacts:
    paths:
      - ./client
      - ./server
